INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 1, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 1, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 1, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 1, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 2, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 2, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 2, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 2, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 3, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 3, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 3, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 3, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 4, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 4, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 4, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 4, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 5, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 6, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 6, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 6, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 6, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 7, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 7, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 7, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 7, 22, 2350, 1532, NOW());
INSERT INTO Buddies (plantType) VALUES ('Unclaimed');
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 8, 20, 2500, 1565, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 8, 25, 2734, 1554, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 8, 27, 3165, 1524, NOW());
INSERT INTO SensorValues (buddy_id, temperature, light, soil, time) VALUES ( 8, 22, 2350, 1532, NOW());